# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: batch/v1
kind: Job
metadata:
  name: { { .Release.Name } }
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: gpu-test-container
          image: { { .Values.image } }
          command: ["sh", "-c"]
          args:
            - |
              echo "GPU test workload starting"
              sleep {{ .Values.sleepDuration }}
              echo "GPU test workload completed"
          resources:
            requests:
              cpu: { { .Values.resources.requests.cpu } }
              memory: { { .Values.resources.requests.memory } }
              amd.com/gpu:
                { { index .Values.resources.requests "amd.com/gpu" | quote } }
            limits:
              cpu: { { .Values.resources.limits.cpu } }
              memory: { { .Values.resources.limits.memory } }
              amd.com/gpu:
                { { index .Values.resources.limits "amd.com/gpu" | quote } }
