# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: airm-agent-webhook
  namespace: airm
spec:
  template:
    spec:
      containers:
        - name: webhook
          workingDir: /code/apps/agent
          command: ["air"]
          ports:
            - $patch: delete
          env:
            - name: AIR_BINARY_NAME
              value: air-webhook
            - name: AIR_CMD
              value: "./cmd/webhooks"
            - name: GOFLAGS
              value: "-mod=vendor"
            - name: GOCACHE
              value: "/go-cache/build"
          livenessProbe:
            $patch: delete
          readinessProbe:
            $patch: delete
          volumeMounts:
            - name: code
              mountPath: /code
            - name: go-build-cache
              mountPath: /go-cache/build
          securityContext:
            $patch: delete
      volumes:
        - name: code
          hostPath:
            path: /code
        - name: go-build-cache
          hostPath:
            path: /tmp/airm-agent-webhook-go-build-cache
            type: DirectoryOrCreate
