# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
        - name: sleep
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["sleep", "{{ .Values.sleepSeconds }}"]
