// Copyright © Advanced Micro Devices, Inc., or its affiliates.
//
// SPDX-License-Identifier: MIT

package messaging

import amqp "github.com/rabbitmq/amqp091-go"

type QueueConfig struct {
	Durable    bool
	AutoDelete bool
	Exclusive  bool
	NoWait     bool
	Args       amqp.Table
}

type ConsumerConfig struct {
	ConsumerTag string // Consumer identifier (empty = auto-generated)
	AutoAck     bool   // Automatically acknowledge messages
	Exclusive   bool   // Exclusive consumer
	NoLocal     bool   // No local delivery
	NoWait      bool   // No wait for server confirmation
	Args        amqp.Table
}

type QoSConfig struct {
	PrefetchCount int  // Number of messages to prefetch
	PrefetchSize  int  // Size of messages to prefetch (0 = unlimited)
	Global        bool // Apply to entire connection vs per-channel
}

func DefaultQueueConfig() QueueConfig {
	return QueueConfig{
		Durable:    true,
		AutoDelete: false,
		Exclusive:  false,
		NoWait:     false,
		Args: amqp.Table{
			"x-queue-type":              "quorum",
			"x-dead-letter-exchange":    "dlx_exchange",
			"x-dead-letter-routing-key": "dlx_key",
		},
	}
}

func DefaultConsumerConfig() ConsumerConfig {
	return ConsumerConfig{
		ConsumerTag: "",    // Auto-generated by RabbitMQ
		AutoAck:     false, // Manual acknowledgment for reliability
		Exclusive:   false, // Allow multiple consumers
		NoLocal:     false, // Allow local delivery
		NoWait:      false, // Wait for server confirmation
		Args:        nil,
	}
}

func DefaultQoSConfig() QoSConfig {
	return QoSConfig{
		PrefetchCount: 1,     // Process one message at a time
		PrefetchSize:  0,     // No size limit
		Global:        false, // Apply per-channel
	}
}
