// Copyright © Advanced Micro Devices, Inc., or its affiliates.
//
// SPDX-License-Identifier: MIT

export const mockAims = [
  {
    id: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
    created_at: '2025-10-07T10:21:32.607Z',
    updated_at: '2025-10-07T10:21:32.607Z',
    created_by: 'string',
    updated_by: 'string',
    image_name: 'string',
    image_tag: '0.1.0-rc',
    image: 'string',
    labels: {
      'com.amd.aim.hfToken.required': 'False',
      'org.opencontainers.image.source': 'https://github.com/silogen/aim-build',
      'org.opencontainers.image.title': 'AIM - DeepSeek-R1',
      'org.opencontainers.image.revision':
        'ebec727adebbf66f8fcbb28180b03f992c220c69',
      'org.opencontainers.image.ref.name': 'ubuntu',
      'org.opencontainers.image.licenses': 'MIT',
      'org.opencontainers.image.version': '0.4.1',
      'org.opencontainers.image.documentation': '',
      'org.opencontainers.image.vendor': 'AMD',
      'org.opencontainers.image.authors': 'aim.team.placeholder.email@amd.com',
      'org.opencontainers.image.created': '2025-10-09T10:13:08+02:00',
      'com.amd.aim.description.full':
        'DeepSeek-R1 is a new generation of reasoning models. DeepSeek-R1 was developed by incorporating "cold-start data" before the reinforcement learning (RL) stage to address issues like repetition and poor readability. This model achieves performance comparable to OpenAI-o1 on math, code, and reasoning tasks. The authors also demonstrate that the reasoning abilities of the large DeepSeek-R1 model can be successfully distilled into smaller, more efficient models. They have open-sourced several distilled models based on the Llama and Qwen architectures.',
      'org.opencontainers.image.description.short':
        'DeepSeek R1 reasoning model trained on diverse data for exceptional reasoning capabilities.',
      'com.amd.aim.model.source':
        'https://huggingface.co/deepseek-ai/DeepSeek-R1',
      'com.amd.aim.model.canonicalName': 'deepseek-ai/DeepSeek-R1',
      'com.amd.aim.model.versions': 'deepseek-ai/DeepSeek-R1',
      'com.amd.aim.model.tags': 'text-generation, chat, reasoning',
      'com.amd.aim.release.notes': '',
    },
    workload: {
      id: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
      created_at: '2025-10-07T10:21:32.607Z',
      updated_at: '2025-10-07T10:21:32.607Z',
      created_by: 'string',
      updated_by: 'string',
      display_name: 'string',
      name: 'string',
      project: {
        id: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        created_at: '2025-10-07T10:21:32.607Z',
        updated_at: '2025-10-07T10:21:32.607Z',
        created_by: 'string',
        updated_by: 'string',
        name: 'tsg50mi891n7t8mgywoi56tl9hnpzv-cmb7kcrlshcn7jjslw6n9ahh3qfxe-4p',
        description: 'string',
        cluster_id: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        status: 'Pending',
        status_reason: 'string',
      },
      status: 'Running',
      type: 'INFERENCE',
      user_inputs: {},
      output: {
        additionalProp1: {},
      },
      allocated_resources: {
        gpu_count: 0,
        vram: 0,
      },
      aim_id: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
    },
  },
  {
    id: '3fa85f64-5717-4562-b3fc-2c963f66afa5',
    created_at: '2025-10-07T10:21:32.607Z',
    updated_at: '2025-10-07T10:21:32.607Z',
    created_by: 'string',
    updated_by: 'string',
    image_name: 'string',
    image_tag: '0.1.0-dev',
    image: 'string',
    labels: {
      'com.amd.aim.hfToken.required': 'False',
      'org.opencontainers.image.source': 'https://github.com/silogen/aim-build',
      'org.opencontainers.image.title': 'AIM - DeepSeek-R2',
      'org.opencontainers.image.revision':
        'ebec727adebbf66f8fcbb28180b03f992c220c69',
      'com.amd.aim.description.full':
        'DeepSeek-R1 is a new generation of reasoning models. DeepSeek-R1 was developed by incorporating "cold-start data" before the reinforcement learning (RL) stage to address issues like repetition and poor readability. This model achieves performance comparable to OpenAI-o1 on math, code, and reasoning tasks. The authors also demonstrate that the reasoning abilities of the large DeepSeek-R1 model can be successfully distilled into smaller, more efficient models. They have open-sourced several distilled models based on the Llama and Qwen architectures.',
      'org.opencontainers.image.description.short':
        'DeepSeek R1 reasoning model trained on diverse data for exceptional reasoning capabilities.',
      'com.amd.aim.model.source':
        'https://huggingface.co/deepseek-ai/DeepSeek-R1',
      'com.amd.aim.model.canonicalName': 'deepseek-ai/DeepSeek-R1',
      'org.opencontainers.image.ref.name': 'ubuntu',
      'org.opencontainers.image.licenses': 'MIT',
      'com.amd.aim.model.versions': 'deepseek-ai/DeepSeek-R1',
      'org.opencontainers.image.version': '0.4.1',
      'com.amd.aim.release.notes': '',
      'org.opencontainers.image.documentation': '',
      'com.amd.aim.model.tags': 'text-generation, chat, reasoning',
      'org.opencontainers.image.vendor': 'AMD',
      'org.opencontainers.image.authors': 'aim.team.placeholder.email@amd.com',
      'org.opencontainers.image.created': '2025-10-09T10:13:08+02:00',
    },
    workload: {
      id: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
      created_at: '2025-10-07T10:21:32.607Z',
      updated_at: '2025-10-07T10:21:32.607Z',
      created_by: 'string',
      updated_by: 'string',
      display_name: 'string',
      name: 'string',
      project: {
        id: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        created_at: '2025-10-07T10:21:32.607Z',
        updated_at: '2025-10-07T10:21:32.607Z',
        created_by: 'string',
        updated_by: 'string',
        name: 'tsg50mi891n7t8mgywoi56tl9hnpzv-cmb7kcrlshcn7jjslw6n9ahh3qfxe-4p',
        description: 'string',
        cluster_id: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        status: 'Pending',
        status_reason: 'string',
      },
      status: 'Deleting',
      type: 'INFERENCE',
      user_inputs: {},
      output: {
        additionalProp1: {},
      },
      allocated_resources: {
        gpu_count: 0,
        vram: 0,
      },
      aim_id: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
    },
  },
  {
    id: '3fa85f64-5717-4562-b3fc-2c963f66afa1',
    created_at: '2025-10-07T10:21:32.607Z',
    updated_at: '2025-10-07T10:21:32.607Z',
    created_by: 'string',
    updated_by: 'string',
    image_name: 'string',
    image_tag: '0.1.0-preview',
    image: 'string',
    labels: {
      'com.amd.aim.hfToken.required': 'False',
      'org.opencontainers.image.source': 'https://github.com/silogen/aim-build',
      'org.opencontainers.image.title': 'AIM - DeepSeek-R3',
      'org.opencontainers.image.revision':
        'ebec727adebbf66f8fcbb28180b03f992c220c69',
      'com.amd.aim.description.full':
        'DeepSeek-R1 is a new generation of reasoning models. DeepSeek-R1 was developed by incorporating "cold-start data" before the reinforcement learning (RL) stage to address issues like repetition and poor readability. This model achieves performance comparable to OpenAI-o1 on math, code, and reasoning tasks. The authors also demonstrate that the reasoning abilities of the large DeepSeek-R1 model can be successfully distilled into smaller, more efficient models. They have open-sourced several distilled models based on the Llama and Qwen architectures.',
      'org.opencontainers.image.description.short':
        'DeepSeek R1 reasoning model trained on diverse data for exceptional reasoning capabilities.',
      'com.amd.aim.model.source':
        'https://huggingface.co/deepseek-ai/DeepSeek-R1',
      'com.amd.aim.model.canonicalName': 'deepseek-ai/DeepSeek-R1',
      'org.opencontainers.image.ref.name': 'ubuntu',
      'org.opencontainers.image.licenses': 'MIT',
      'com.amd.aim.model.versions': 'deepseek-ai/DeepSeek-R1',
      'org.opencontainers.image.version': '0.4.1',
      'com.amd.aim.release.notes': '',
      'org.opencontainers.image.documentation': '',
      'com.amd.aim.model.tags': 'text-generation, chat, reasoning',
      'org.opencontainers.image.vendor': 'AMD',
      'org.opencontainers.image.authors': 'aim.team.placeholder.email@amd.com',
      'org.opencontainers.image.created': '2025-10-09T10:13:08+02:00',
    },
    workload: {
      id: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
      created_at: '2025-10-07T10:21:32.607Z',
      updated_at: '2025-10-07T10:21:32.607Z',
      created_by: 'string',
      updated_by: 'string',
      display_name: 'string',
      name: 'string',
      project: {
        id: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        created_at: '2025-10-07T10:21:32.607Z',
        updated_at: '2025-10-07T10:21:32.607Z',
        created_by: 'string',
        updated_by: 'string',
        name: 'tsg50mi891n7t8mgywoi56tl9hnpzv-cmb7kcrlshcn7jjslw6n9ahh3qfxe-4p',
        description: 'string',
        cluster_id: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
        status: 'Pending',
        status_reason: 'string',
      },
      status: 'Pending',
      type: 'INFERENCE',
      user_inputs: {},
      output: {
        additionalProp1: {},
      },
      allocated_resources: {
        gpu_count: 0,
        vram: 0,
      },
      aim_id: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
    },
  },
  {
    id: '3fa85f64-5717-4562-b3fc-2c963f66afa2',
    created_at: '2025-10-07T10:21:32.607Z',
    updated_at: '2025-10-07T10:21:32.607Z',
    created_by: 'string',
    updated_by: 'string',
    image_name: 'string',
    image_tag: 'string',
    image: 'string',
    labels: {
      'com.amd.aim.hfToken.required': 'False',
      'org.opencontainers.image.source': 'https://github.com/silogen/aim-build',
      'org.opencontainers.image.title': 'DeepSeek-R4',
      'org.opencontainers.image.revision':
        'ebec727adebbf66f8fcbb28180b03f992c220c69',
      'com.amd.aim.description.full':
        'DeepSeek-R4 sdfsd eff is a new generation of reasoning models. DeepSeek-R4 was developed by incorporating "cold-start data" before the reinforcement learning (RL) stage to address issues like repetition and poor readability. This model achieves performance comparable to OpenAI-o1 on math, code, and reasoning tasks. The authors also demonstrate that the reasoning abilities of the large DeepSeek-R1 model can be successfully distilled into smaller, more efficient models. They have open-sourced several distilled models based on the Llama and Qwen architectures.',
      'org.opencontainers.image.description.short':
        'DeepSeek R4 asa sdf reasoning model trained on diverse data for exceptional reasoning capabilities.',
      'com.amd.aim.model.source':
        'https://huggingface.co/deepseek-ai/DeepSeek-R1',
      'com.amd.aim.model.canonicalName': 'deepseek-ai/DeepSeek-R1',
      'org.opencontainers.image.ref.name': 'ubuntu',
      'org.opencontainers.image.licenses': 'MIT',
      'com.amd.aim.model.versions': 'deepseek-ai/DeepSeek-R1',
      'org.opencontainers.image.version': '0.4.1',
      'com.amd.aim.release.notes': '',
      'org.opencontainers.image.documentation': '',
      'com.amd.aim.model.tags': 'text-generation, chat, reasoning, whoisoning',
      'org.opencontainers.image.vendor': 'AMD',
      'org.opencontainers.image.authors': 'aim.team.placeholder.email@amd.com',
      'org.opencontainers.image.created': '2025-10-09T10:13:08+02:00',
    },
  },
];
